[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
test4 = "8BESTtLTqB8vUkiEPkC72V5DXwWDidJNXZvZsmMrQvZ4"

[programs.devnet]
test4 = "8BESTtLTqB8vUkiEPkC72V5DXwWDidJNXZvZsmMrQvZ4"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "testnet"
cluster = "devnet"
#cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
