[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
test4 = "H1GnE4nXfX131eMdX4Fn1DLvnwmFDRy4jLwCFJwo197s"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "testnet"
cluster = "devnet"
#cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
